apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  namespace: dev
  labels:
    app: demo-service
    dev/version: '${RELEASE_VERSION}'
  annotations:
    configmap.reloader.stakater.com/reload: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
        dev/version: '18'
    spec:
      serviceAccountName: demo-service
      containers:
        - name: demo-service
          image: ${IMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: demo-service
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: worker
  metadata:
    metadata:
      labels:
        dev/version: ${RELEASE_VERSION}
