apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-service-destination
  namespace: dev
spec:
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTAL
  host: demo-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
