apiVersion: v1
data:
    username: ENC[AES256_GCM,data:z2uuxMMUDUs=,iv:/j9s26k/3dDAJQwkUxTrGmMboWzBCKF4uzt4WRqMI+Y=,tag:xxp8dmtwjXAZfjRPaANSMg==,type:str]
    password: ENC[AES256_GCM,data:9HmaQvl6MqvlVQDb,iv:wDd1r7ruZHViVmJfFjPCMn8BhqtYctagskH+UehtpwI=,tag:JN5i6ksaPELjCbtxKbUEKw==,type:str]
kind: Secret
metadata:
    name: test-svc-blue
    namespace: dev
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:093113466774:key/15de53d9-54ea-4c58-b7e1-244faf1e528a
          created_at: "2021-11-13T12:31:27Z"
          enc: AQICAHjzSN03sx5ISt+cYLKX60XgK/rKw/ZmxsnNNe0lD5DclQG5ju4/evGxtNMliNHTuUvzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFc1EFJVadKFj36DmAgEQgDs0Ycb4U13wjENETfDjNzKPSOHC/fuV001rLjpM/7KlYadOHi8hYG2mMoEx0aQOuW+vk3EuGNBuKM8Dng==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T12:31:28Z"
    mac: ENC[AES256_GCM,data:nZPvVw4H6leloqztmYdwG8lKd6hDtgFyuFksO1Jm8hTddZ4WCLoY7fH6tjNtNNGbU5a7iJ1vy2SYh0ENtHBpAKCc2PWvLOAW/KaIxgHNrK+7cwctXAcZoJEVywTVPbImPHzlOvmH2SL01bNS+wElIfUj3EiYsj+mpuNQaAw5ApM=,iv:mYc90HEP+v7X0oEWt858FJHTiE6jVnbhWXfhYOXf2y4=,tag:r19yas5XncrIa1Swh6NWiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
