apiVersion: v1
data:
    username: ENC[AES256_GCM,data:TBq1Oukeoo0YL/aYxwhIlw==,iv:ATsSK2c750nkdXwp8aX68kiyWu5LlS4/OsOHTrBPaEE=,tag:7RcRCaT3i/KtRwlTI5tu7Q==,type:str]
    password: ENC[AES256_GCM,data:d/1l8+jgwS2rwQ6X7kPcBQumBpI=,iv:TWSktjKTZMWNaGJDWJyPbkDOXpqb4yy2Rp15ANnfVug=,tag:8A9APevZyo6ur9iL6rRB9w==,type:str]
kind: Secret
metadata:
    name: test-svc-green
    namespace: dev
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:093113466774:key/15de53d9-54ea-4c58-b7e1-244faf1e528a
          created_at: "2021-11-13T15:02:00Z"
          enc: AQICAHjzSN03sx5ISt+cYLKX60XgK/rKw/ZmxsnNNe0lD5DclQG24Pzg4AquJzS6Eja2FttQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwfeUjIplnFyqrhtxAgEQgDtqbV1c/Ufh9kpVpvgWSuQLfYx8Bb6CESvRqQsisvu93KU1ofp97PeSxYuY9ctdkkDTmWJTQMQk1Yd8jA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T15:02:00Z"
    mac: ENC[AES256_GCM,data:ifnMjn4pgff4IX/J4jlvTxk86WEG4dRl6i4kre2ULzQ/N45aH62x33RhvAuAOUiftV5V8jOtuhO1dU51N/0JkVjk7ySJQDRGVOYx/BwZi0GQmFWxnbXRxjGLEIJFdT8N+wrxB6gCsLPkmjTMO9dMPnR8OrNbIYgch179H76Ft04=,iv:u21kmZ/lCYnUux7O/6/adMhrPzL+PZe4Np82fXlOXRA=,tag:xe5ro6NXeDixTMo+6uUuGw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
