apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: dev
  labels:
    app: svc
    service: svc
spec:
  selector:
    app: svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
