apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: svc
  namespace: dev
spec:
  hosts:
    - svc.yeonghoo2.com
  gateways:
    - svc
  http:
    - route:
        - destination:
            host: svc
            subset: green
