apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-svc
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - internal-svc.yeonghoo2.com