apiVersion: v1
kind: ConfigMap
metadata:
    name: test-svc-green
    namespace: dev
data:
    env: ENC[AES256_GCM,data:U+JR,iv:tFM5Z9nOgx/3/+LkSMVnVuDM4G/ObnRslGSUMRg4t78=,tag:BHoSHkLTJWayMdVh40mhMQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:093113466774:key/15de53d9-54ea-4c58-b7e1-244faf1e528a
          created_at: "2021-11-13T12:31:23Z"
          enc: AQICAHjzSN03sx5ISt+cYLKX60XgK/rKw/ZmxsnNNe0lD5DclQFuW1PmoQBOXoMnK/rkUVkgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9ZlOYTgBRlwXbYgXAgEQgDvXmjXfKCdoebnvu9fkxRIkm4h2w1wC4mOyuCaxeXO+fdQf71+G707Y/oebGocoatamJRLM9pBhGAwbwg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T12:31:23Z"
    mac: ENC[AES256_GCM,data:h26EC6VfAmWk8W9wrUlxel1o50DL0HeNZfavlX5mwKoK/mpeT0SLtit/R/mNoOlZ2usaOriAzzawxQu0gT7sBN0GBNddXjQjV7bB7Jm24n4l2qyeco/eddM/I5xDjXKFrokDlqqIJJD9yftGmm+zWv8/QOlM9SRO9wGjg8L0p3w=,iv:P2EA+E1REogbw1qzIarV4TJkJfnxxwoGUSSr5mzxvbM=,tag:WTvE0Q7EN5JIWNnAvL3C/w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
